FROM ubuntu:20.04
# Ensure apt is in non-interactive to avoid prompts
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  # Remove imagemagick due to https://security-tracker.debian.org/tracker/CVE-2019-10131
  && apt-get -y install python3.9-minimal
